#ifndef OSXINTERGATION_GLOBAL_H
#define OSXINTERGATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OSXINTEGRATION_LIBRARY)
#  define OSXINTERGATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OSXINTERGATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OSXINTERGATION_GLOBAL_H
